apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  annotations:
    loki.grafana.com/rulesDiscoveredAt: '2024-04-10T13:36:42Z'
  creationTimestamp: '2024-04-10T00:48:50Z'
  generation: 1
  managedFields:
    - apiVersion: loki.grafana.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:hashRing':
            .: {}
            'f:type': {}
          'f:limits':
            .: {}
            'f:global':
              .: {}
              'f:queries':
                .: {}
                'f:queryTimeout': {}
          'f:managementState': {}
          'f:size': {}
          'f:storage':
            .: {}
            'f:schemas': {}
            'f:secret':
              .: {}
              'f:name': {}
              'f:type': {}
          'f:storageClassName': {}
          'f:tenants':
            .: {}
            'f:mode': {}
      manager: Mozilla
      operation: Update
      time: '2024-04-10T00:48:50Z'
    - apiVersion: loki.grafana.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:loki.grafana.com/rulesDiscoveredAt': {}
      manager: manager
      operation: Update
      time: '2024-04-10T13:36:42Z'
    - apiVersion: loki.grafana.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:components':
            .: {}
            'f:compactor':
              .: {}
              'f:Ready': {}
            'f:distributor':
              .: {}
              'f:Ready': {}
            'f:gateway':
              .: {}
              'f:Ready': {}
            'f:indexGateway':
              .: {}
              'f:Ready': {}
            'f:ingester':
              .: {}
              'f:Ready': {}
            'f:querier':
              .: {}
              'f:Ready': {}
            'f:queryFrontend':
              .: {}
              'f:Ready': {}
          'f:conditions': {}
          'f:storage':
            .: {}
            'f:credentialMode': {}
            'f:schemas': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2024-04-10T13:36:42Z'
  name: loki
  namespace: netobserv
  resourceVersion: '723090'
  uid: f1772b7f-9cbd-4994-9eb6-ebb13593b462
spec:
  hashRing:
    type: memberlist
  limits:
    global:
      queries:
        queryTimeout: 3m
  managementState: Managed
  size: 1x.small
  storage:
    schemas:
      - effectiveDate: '2020-10-11'
        version: v11
    secret:
      name: lokistack-dev-s3
      type: s3
  storageClassName: ocs-external-storagecluster-ceph-rbd
  tenants:
    mode: openshift-network
