apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
  resourceVersion: '273648'
  uid: 15a93a39-46e4-4a3e-8ca6-b78c24b6503a
spec:
  agent:
    ebpf:
      cacheActiveTimeout: 5s
      cacheMaxFlows: 100000
      excludeInterfaces:
        - lo
      imagePullPolicy: IfNotPresent
      kafkaBatchSize: 1048576
      logLevel: info
      resources:
        limits:
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 50Mi
      sampling: 50
    ipfix:
      cacheActiveTimeout: 20s
      cacheMaxFlows: 400
      clusterNetworkOperator:
        namespace: openshift-network-operator
      ovnKubernetes:
        containerName: ovnkube-node
        daemonSetName: ovnkube-node
        namespace: ovn-kubernetes
      sampling: 400
    type: eBPF
  consolePlugin:
    autoscaler:
      maxReplicas: 3
      status: Disabled
    enable: true
    imagePullPolicy: IfNotPresent
    logLevel: info
    portNaming:
      enable: true
    quickFilters:
      - default: true
        filter:
          flow_layer: app
        name: Applications
      - filter:
          flow_layer: infra
        name: Infrastructure
      - default: true
        filter:
          dst_kind: Pod
          src_kind: Pod
        name: Pods network
      - filter:
          dst_kind: Service
        name: Services network
    replicas: 1
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 50Mi
  deploymentModel: Direct
  exporters: []
  kafka:
    address: ''
    sasl:
      clientIDReference: {}
      clientSecretReference: {}
      type: Disabled
    tls:
      caCert: {}
      userCert: {}
    topic: ''
  loki:
    writeTimeout: 10s
    microservices:
      ingesterUrl: 'http://loki-distributor:3100/'
      querierUrl: 'http://loki-query-frontend:3100/'
      tenantID: netobserv
      tls:
        caCert: {}
        userCert: {}
    enable: true
    mode: LokiStack
    manual:
      authToken: Disabled
      ingesterUrl: 'http://loki:3100/'
      querierUrl: 'http://loki:3100/'
      statusTls:
        caCert: {}
        userCert: {}
      tenantID: netobserv
      tls:
        caCert: {}
        userCert: {}
    lokiStack:
      name: loki
      namespace: netobserv
    readTimeout: 30s
    monolithic:
      tenantID: netobserv
      tls:
        caCert: {}
        userCert: {}
      url: 'http://loki:3100/'
    writeBatchWait: 1s
    writeBatchSize: 102400
  namespace: netobserv
  processor:
    logLevel: info
    metrics:
      server:
        port: 9102
        tls:
          type: Disabled
    resources:
      limits:
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 100Mi
    multiClusterDeployment: false
    kafkaConsumerQueueCapacity: 1000
    imagePullPolicy: IfNotPresent
    kafkaConsumerAutoscaler:
      maxReplicas: 3
      status: Disabled
    logTypes: Flows
    kafkaConsumerReplicas: 3
    kafkaConsumerBatchSize: 10485760
